# Generated by Django 2.1.4 on 2019-01-08 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_1', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('file_2', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_secondary', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.Publisher')),
            ],
        ),
    ]
